import { useState } from 'react';
import { DollarSign, TrendingDown, Calculator, Copy, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import type { CostEstimate } from '@/types';

interface CostEstimateCardProps {
  estimate: CostEstimate;
}

export default function CostEstimateCard({ estimate }: CostEstimateCardProps) {
  const [copied, setCopied] = useState(false);
  const [showDetails, setShowDetails] = useState(false);

  const handleCopyReport = () => {
    const report = `
Deadlog Cost Analysis Report
============================

Estimated Monthly Cost: $${estimate.monthlyCost.toFixed(2)}
Potential Annual Savings: $${estimate.annualSavings.toFixed(2)}

Dead Endpoints: ${estimate.deadEndpointCount}
Low Traffic Endpoints: ${estimate.lowTrafficCount}

Assumptions:
- Cost per request: $${estimate.assumptions.costPerRequest}
- Estimated requests per month: ${estimate.assumptions.requestsPerMonth.toLocaleString()}

Generated by Deadlog
    `.trim();

    navigator.clipboard.writeText(report).then(() => {
      setCopied(true);
      toast.success('Report copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(amount);
  };

  return (
    <div className="card-dark p-6">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-lime/10 flex items-center justify-center">
            <DollarSign className="w-5 h-5 text-lime" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-white">Cost Impact</h3>
            <p className="text-sm text-muted-foreground">
              Estimated waste from unused endpoints
            </p>
          </div>
        </div>
        
        <div className="flex gap-2">
          <Button
            onClick={handleCopyReport}
            variant="outline"
            size="sm"
            className="border-deadlog-700"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 mr-2 text-lime" />
                Copied
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 mr-2" />
                Copy Report
              </>
            )}
          </Button>
        </div>
      </div>

      <div className="grid md:grid-cols-3 gap-4 mb-6">
        <div className="bg-deadlog-800/50 rounded-xl p-4">
          <p className="text-sm text-muted-foreground mb-1">Monthly Cost</p>
          <p className="text-2xl font-display font-bold text-red-400">
            {formatCurrency(estimate.monthlyCost)}
          </p>
        </div>
        
        <div className="bg-deadlog-800/50 rounded-xl p-4">
          <p className="text-sm text-muted-foreground mb-1">Annual Savings</p>
          <p className="text-2xl font-display font-bold text-lime">
            {formatCurrency(estimate.annualSavings)}
          </p>
        </div>
        
        <div className="bg-deadlog-800/50 rounded-xl p-4">
          <p className="text-sm text-muted-foreground mb-1">Problem Endpoints</p>
          <p className="text-2xl font-display font-bold text-white">
            {estimate.deadEndpointCount + estimate.lowTrafficCount}
          </p>
        </div>
      </div>

      <button
        onClick={() => setShowDetails(!showDetails)}
        className="flex items-center gap-2 text-sm text-muted-foreground hover:text-white transition-colors"
      >
        <Calculator className="w-4 h-4" />
        {showDetails ? 'Hide calculation details' : 'Show calculation details'}
      </button>

      {showDetails && (
        <div className="mt-4 pt-4 border-t border-deadlog-800">
          <div className="grid md:grid-cols-2 gap-4 text-sm">
            <div>
              <p className="text-muted-foreground mb-2">Assumptions</p>
              <ul className="space-y-1">
                <li className="flex justify-between">
                  <span>Cost per request:</span>
                  <span className="font-mono">${estimate.assumptions.costPerRequest}</span>
                </li>
                <li className="flex justify-between">
                  <span>Est. requests/month:</span>
                  <span className="font-mono">{estimate.assumptions.requestsPerMonth.toLocaleString()}</span>
                </li>
              </ul>
            </div>
            <div>
              <p className="text-muted-foreground mb-2">Breakdown</p>
              <ul className="space-y-1">
                <li className="flex justify-between">
                  <span>Dead endpoints:</span>
                  <span className="font-mono text-red-400">{estimate.deadEndpointCount}</span>
                </li>
                <li className="flex justify-between">
                  <span>Low traffic:</span>
                  <span className="font-mono text-yellow-400">{estimate.lowTrafficCount}</span>
                </li>
              </ul>
            </div>
          </div>
          
          <div className="mt-4 p-4 bg-deadlog-800/30 rounded-lg">
            <p className="text-sm text-muted-foreground">
              <TrendingDown className="w-4 h-4 inline mr-2" />
              These estimates assume logs cover approximately 7 days of traffic. 
              Actual savings may vary based on your infrastructure costs.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
